org

diff --git a/cookbook/kitchen.yml b/cookbook/kitchen.yml
--- a/cookbook/kitchen.yml
+++ b/cookbook/kitchen.yml
@@ -29,18 +29,18 @@ suites:
 
 lifecycle:
   post_create:
-    local: |
+  - local: |
       echo "Generate FIPS Key"
       mkdir -m 700 -p keys
       ssh-keygen -t ed25519 -f keys/fips_key -o -a 100 -N ""
       #chmod g-rwx,o-rwx keys/*
       #yq eval '.ssh_key = "keys/fips_key"' -i .kitchen/default-rhel-9.yml
       export PUB_KEY=$(cat keys/fips_key.pub)
-    remote: |
+  - remote: |
       echo "[INFO] Importing Public Key to SSH Authorized Keys"
       echo "<%= ENV['PUB_KEY'] %>" >> ~/.ssh/authorized_keys
       echo "[INFO] Attempting Red Hat subscription registration..."
-      sudo subscription-manager register --username "<%= ENV['REDHAT_USERNAME'] %>" --password "<%= ENV['REDHAT_PASSWORD'] %>" || echo "[WARN] Registration failed"
+      sudo subscription-manager register --username "<%= ENV['REDHAT_USERNAME'] %>" --password "<%= ENV['REDHAT_PASSWORD'] %>" --force || echo "[WARN] Registration failed"
       echo "[INFO] Installing basic utilities..."
       yum install -y sudo hostname lsof && yum clean all || echo "[WARN] Failed to install packages"
       yum update
